### PR TITLE
Check that list of device configuration has at least one element

### PR DESCRIPTION
**Pull request by skuenzli**
Check that list of device configuration has at least one element before inspecting first element

### CODE REVIEW

**Comment by EnriqueHernandezL** [comment]
Thanks for the pull request. Unfortunately there is a syntax error due to the missing `if` keyword.

**Comment by skuenzli** [comment]
Sorry about that. There was a copy-paste error from my local copy. But I'm sure you get the gist.

**Comment by EnriqueHernandezL** [comment]
Sure. I just commited it in https://github.com/SySS-Research/azurenum/commit/a00422a3905694093a9e8dddb59a45216b3faa39

Thanks!

**Comment by skuenzli** [comment]
Super - thank you!

**Pull request closed without merging**
